// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAntqYZl5tgr-8Bz3VceE5dtDU4Gd7PWIs',
    appId: '1:755027068677:web:2b6ea5a82edc621582996c',
    messagingSenderId: '755027068677',
    projectId: 'time-since-app',
    authDomain: 'time-since-app.firebaseapp.com',
    storageBucket: 'time-since-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA68SvAxgkGr9gq0IEsOwxTdiUVxQhxMjk',
    appId: '1:755027068677:android:b7c5044e3aaca41382996c',
    messagingSenderId: '755027068677',
    projectId: 'time-since-app',
    storageBucket: 'time-since-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDdok2Uy_xFuStJAFt_HFkBJTBiIjcs1pk',
    appId: '1:755027068677:ios:2faada5c804c9c0082996c',
    messagingSenderId: '755027068677',
    projectId: 'time-since-app',
    storageBucket: 'time-since-app.firebasestorage.app',
    iosBundleId: 'com.example.timeSince',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDdok2Uy_xFuStJAFt_HFkBJTBiIjcs1pk',
    appId: '1:755027068677:ios:2faada5c804c9c0082996c',
    messagingSenderId: '755027068677',
    projectId: 'time-since-app',
    storageBucket: 'time-since-app.firebasestorage.app',
    iosBundleId: 'com.example.timeSince',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAntqYZl5tgr-8Bz3VceE5dtDU4Gd7PWIs',
    appId: '1:755027068677:web:70032b929a11cf0a82996c',
    messagingSenderId: '755027068677',
    projectId: 'time-since-app',
    authDomain: 'time-since-app.firebaseapp.com',
    storageBucket: 'time-since-app.firebasestorage.app',
  );
}
